# Generated by Django 3.1.1 on 2020-09-26 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('numero_guia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Guia')),
                ('data_consulta', models.DateField(verbose_name='Data da Consulta')),
                ('valor_consulta', models.FloatField(verbose_name='Valor da Consulta')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ('numero_guia',),
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('cod_medico', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código')),
                ('nome_medico', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ('cod_medico',),
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_exame', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_exame', models.FloatField(verbose_name='Valor do Exame')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.consulta', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
                'ordering': ('consulta__numero_guia',),
            },
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medico', verbose_name='Médico'),
        ),
    ]
